"""GitHub PR management — create pull requests for refactors."""

import os
import subprocess
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional

import httpx
from rich.console import Console

console = Console()

GITHUB_API = "https://api.github.com"


@dataclass
class PRMetadata:
    """Metadata for creating a pull request."""

    title: str
    summary: str
    affected_files: List[str]
    estimated_risk: str
    steps_count: int
    steps_completed: int


def build_pr_body(meta: PRMetadata) -> str:
    """Build the PR description body."""
    risk = meta.estimated_risk.capitalize()
    files_list = "\n".join(f"- `{f}`" for f in meta.affected_files[:20])
    truncated = ""
    if len(meta.affected_files) > 20:
        truncated = f"\n- ... and {len(meta.affected_files) - 20} more files"

    return f"""## RepoSurgeon Refactor

{meta.summary}

### Summary
- **Risk Level:** {risk}
- **Steps Executed:** {meta.steps_completed} / {meta.steps_count}
- **Files Changed:** {len(meta.affected_files)}

### Changed Files
{files_list}{truncated}

### Review Notes
This refactor was planned and executed by [RepoSurgeon](https://github.com/reposurgeon),
an autonomous codebase refactoring agent. Please review carefully:

1. Verify that the refactor achieves the intended change
2. Check for any missed edge cases or references
3. Run the test suite before merging
4. Consider running integration/end-to-end tests

---
*Generated by RepoSurgeon v0.1.0*
"""


def create_pr(
    repo_path: Path,
    meta: PRMetadata,
    branch: str,
    base_branch: str = "main",
    token: Optional[str] = None,
) -> str:
    """Create a GitHub pull request.

    Args:
        repo_path: Path to the cloned repository
        meta: PR metadata
        branch: Feature branch name
        base_branch: Base branch to merge into
        token: GitHub personal access token (or GITHUB_TOKEN env var)

    Returns:
        URL of the created pull request

    Raises:
        RuntimeError: If PR creation fails
    """
    token = token or os.getenv("GITHUB_TOKEN")
    if not token:
        raise RuntimeError(
            "GitHub token required. Set GITHUB_TOKEN env var or pass token parameter."
        )

    # Extract owner/repo from git remote
    result = subprocess.run(
        ["git", "remote", "get-url", "origin"],
        cwd=repo_path,
        capture_output=True,
        text=True,
    )
    remote_url = result.stdout.strip()

    # Parse owner/repo from URL
    # Handles: https://github.com/owner/repo.git and git@github.com:owner/repo.git
    if "github.com" not in remote_url:
        raise RuntimeError(f"Not a GitHub repository: {remote_url}")

    remote_url = remote_url.replace("https://github.com/", "").replace("git@github.com:", "")
    remote_url = remote_url.rstrip("/")
    if remote_url.endswith(".git"):
        remote_url = remote_url[:-4]
    owner, repo = remote_url.split("/")[-2:]

    body = build_pr_body(meta)

    console.print(f"[bold]Creating PR on {owner}/{repo}...[/]")

    response = httpx.post(
        f"{GITHUB_API}/repos/{owner}/{repo}/pulls",
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        },
        json={
            "title": meta.title,
            "body": body,
            "head": branch,
            "base": base_branch,
        },
    )

    if response.status_code == 201:
        pr_url = response.json()["html_url"]
        console.print(f"[green bold]PR created: {pr_url}[/]")
        return pr_url
    else:
        raise RuntimeError(
            f"PR creation failed ({response.status_code}): {response.text}"
        )
